/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2025-04-03 16:18:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/GitHub/my_spring/port/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/GitHub/my_spring/port/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1740406374744L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" integrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\" crossorigin=\"anonymous\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("<title>=== SHOP ===</title>\r\n");
      out.write("<script>\r\n");
      out.write("function replyList(){\r\n");
      out.write("	var gdsNum = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\r\n");
      out.write("	//비동기식 데이터 요청\r\n");
      out.write("	$.getJSON(\"/shop/view/replyList\" + \"?n=\" + gdsNum, function(data){\r\n");
      out.write("		var str = \"\";//초기화\r\n");
      out.write("		$(data).each(function(){\r\n");
      out.write("			console.log(data);\r\n");
      out.write("			//날짜 데이터를 보기 쉽게 변환\r\n");
      out.write("			var repDate = new Date(this.repDate);\r\n");
      out.write("			repdate = repDate.toLocaleDateString(\"ko-KR\")\r\n");
      out.write("	//html코드 조립\r\n");
      out.write("	str += \"<li data-repNum='\" + this.repNum + \"'class='list-group-item'>\"\r\n");
      out.write("	+ \"<div class=''>\"\r\n");
      out.write("	+ \"<p class=''>\" + this.userName + \"</p>\"\r\n");
      out.write("	+ \"<p class='mx-3'>\" + repDate + \"</p>\"\r\n");
      out.write("	+ \"</div>\"\r\n");
      out.write("	+ \"<div class='replyContent'>\"+this.repCon+\"</div>\"\r\n");
      out.write("	+\"");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	+\"</li>\";\r\n");
      out.write("		});\r\n");
      out.write("	$(\"section.replyList ul\").html(str);\r\n");
      out.write("	});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/replylist.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm bg-light  fixed-top\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<a class=\"navbar-brand\" href=\"/\">Shop</a>\r\n");
      out.write("<!-- 토글버튼  -->\r\n");
      out.write("<button class=\"navbar-toggler\" data-bs-toggle=\"collapse\" data-bs-target=\"#mynavbar\">\r\n");
      out.write("<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 회원가입 변수 로그인 했을때와 하지 않았을때-->\r\n");
      out.write("<div class=\"collapse navbar-collapse\" id=\"mynavbar\">\r\n");
      out.write("<ul class=\"navbar-nav me-auto align-items-center\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<!-- 로그인을 했을때 -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("<form class=\"d-flex \">\r\n");
      out.write("\r\n");
      out.write("<div class=\"btn-group\">\r\n");
      out.write("<input class=\"form-control\" type=\"text\" placeholder=\"Search\"/>\r\n");
      out.write("<button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<!--  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>-->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/daum.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/include/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/include/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/include/header.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/include/header.jsp(36,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\"//세션이 있어야만 수정삭제가 가능\r\n");
          out.write("	+ \"<div class='replyFooter my-3'>\"\r\n");
          out.write("	+ \"<button type='button' class='modify btn btn-outline-secondary' data-repNum='\"+this.repNum+\"'>M</button>\"\r\n");
          out.write("	+ \"<button type='button' class='delete btn btn-outline-secondary mx-3' data-repNum='\"+this.repNum+\"'>D</button>\"\r\n");
          out.write("	+ \"</div>\"\r\n");
          out.write("	+\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/include/header.jsp(70,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<!-- 로그인을 하지 않으면 -->\r\n");
          out.write("		<li class=\"nav-item\">\r\n");
          out.write("			<a class=\"nav-link\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/signin\">login</a>\r\n");
          out.write("		</li>\r\n");
          out.write("		<li class=\"nav-item\">\r\n");
          out.write("			<a class=\"nav-link\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/signup\">join</a>\r\n");
          out.write("		</li>\r\n");
          out.write("		<li class=\"nav-item\">\r\n");
          out.write("		<a class=\"\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/shop/list?c=101&l=2\">\r\n");
          out.write("		상품보러가기\r\n");
          out.write("		</a> \r\n");
          out.write("		</li>\r\n");
          out.write("\r\n");
          out.write(" \r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/include/header.jsp(86,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("    <!-- Nav Item - User Information -->\r\n");
          out.write("    <li class=\"nav-item dropdown no-arrow\">\r\n");
          out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("            <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\"></span>\r\n");
          out.write("            <img class=\"img-profile rounded-circle\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/crono.png\" style=\"width:30px; height:30px;\">\r\n");
          out.write("        </a>\r\n");
          out.write("        <!-- Dropdown - User Information -->\r\n");
          out.write("        <div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"userDropdown\">\r\n");
          out.write("            <a class=\"dropdown-item\" href=\"#\">\r\n");
          out.write("                <i class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
          out.write("                Profile\r\n");
          out.write("            </a>\r\n");
          out.write("            <a class=\"dropdown-item\" href=\"#\">\r\n");
          out.write("                <i class=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
          out.write("                Settings\r\n");
          out.write("            </a>\r\n");
          out.write("            <a class=\"dropdown-item\" href=\"#\">\r\n");
          out.write("                <i class=\"fas fa-list fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
          out.write("                Activity Log\r\n");
          out.write("            </a>\r\n");
          out.write("            <div class=\"dropdown-divider\"></div>\r\n");
          out.write("            <a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\">\r\n");
          out.write("                <i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
          out.write("                Logout\r\n");
          out.write("            </a>\r\n");
          out.write("        </div>\r\n");
          out.write("    </li>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("    <li class=\"nav-item\">\r\n");
          out.write("        <span class=\"fw-bold\">\r\n");
          out.write("        ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&nbsp;님 환영합니다\r\n");
          out.write("        </span>\r\n");
          out.write("    </li>\r\n");
          out.write("    \r\n");
          out.write("        <div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
          out.write("     \r\n");
          out.write("		<li class=\"nav-item\">\r\n");
          out.write("<a class=\"nav-link fw-bold\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/shop/list?c=1&l=2\">쇼핑몰 상품보러가기</a>\r\n");
          out.write("		</li>\r\n");
          out.write("		<li class=\"nav-item\">\r\n");
          out.write("			<a class=\"nav-link\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/shop/cartList\">카트리스트</a>\r\n");
          out.write("		</li>\r\n");
          out.write("		<li class=\"nav-item\">\r\n");
          out.write("			<a class=\"nav-link\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/shop/orderList\">주문리스트</a>\r\n");
          out.write("		</li>\r\n");
          out.write("		<li class=\"nav-item\">\r\n");
          out.write("			<a class=\"nav-link\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/signout\">logout</a>\r\n");
          out.write("		</li>\r\n");
          out.write("\r\n");
          out.write("           <!-- Nav Item - Search Dropdown (Visible Only XS) -->\r\n");
          out.write("           <li class=\"nav-item dropdown no-arrow d-sm-none\">\r\n");
          out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                <i class=\"fas fa-search fa-fw\"></i>\r\n");
          out.write("            </a>\r\n");
          out.write("            <!-- Dropdown - Messages -->\r\n");
          out.write("            <div class=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\" aria-labelledby=\"searchDropdown\">\r\n");
          out.write("                <form class=\"form-inline mr-auto w-100 navbar-search\">\r\n");
          out.write("                    <div class=\"input-group\">\r\n");
          out.write("                        <input type=\"text\" class=\"form-control bg-light border-0 small\" placeholder=\"Search for...\" aria-label=\"Search\" aria-describedby=\"basic-addon2\">\r\n");
          out.write("                        <div class=\"input-group-append\">\r\n");
          out.write("                            <button class=\"btn btn-primary\" type=\"button\">\r\n");
          out.write("                                \r\n");
          out.write("                            </button>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </form>\r\n");
          out.write("            </div>\r\n");
          out.write("        </li>\r\n");
          out.write("\r\n");
          out.write("        <!-- Nav Item - Alerts -->\r\n");
          out.write("        <li class=\"nav-item dropdown no-arrow mx-1\">\r\n");
          out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                <i class=\"fas fa-bell fa-fw\"></i>\r\n");
          out.write("                <!-- Counter - Alerts -->\r\n");
          out.write("                <span class=\"badge badge-danger badge-counter\">3+</span>\r\n");
          out.write("            </a>\r\n");
          out.write("            <!-- Dropdown - Alerts -->\r\n");
          out.write("            <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"alertsDropdown\">\r\n");
          out.write("                <h6 class=\"dropdown-header\">\r\n");
          out.write("                    Alerts Center\r\n");
          out.write("                </h6>\r\n");
          out.write("                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
          out.write("                    <div class=\"mr-3\">\r\n");
          out.write("                        <div class=\"icon-circle bg-primary\">\r\n");
          out.write("                            <i class=\"fas fa-file-alt text-white\"></i>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div>\r\n");
          out.write("                        <div class=\"small text-gray-500\">December 12, 2019</div>\r\n");
          out.write("                        <span class=\"font-weight-bold\">A new monthly report is ready to download!</span>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </a>\r\n");
          out.write("                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
          out.write("                    <div class=\"mr-3\">\r\n");
          out.write("                        <div class=\"icon-circle bg-success\">\r\n");
          out.write("                            <i class=\"fas fa-donate text-white\"></i>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div>\r\n");
          out.write("                        <div class=\"small text-gray-500\">December 7, 2019</div>\r\n");
          out.write("                        $290.29 has been deposited into your account!\r\n");
          out.write("                    </div>\r\n");
          out.write("                </a>\r\n");
          out.write("                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
          out.write("                    <div class=\"mr-3\">\r\n");
          out.write("                        <div class=\"icon-circle bg-warning\">\r\n");
          out.write("                            <i class=\"fas fa-exclamation-triangle text-white\"></i>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div>\r\n");
          out.write("                        <div class=\"small text-gray-500\">December 2, 2019</div>\r\n");
          out.write("                        Spending Alert: We've noticed unusually high spending for your account.\r\n");
          out.write("                    </div>\r\n");
          out.write("                </a>\r\n");
          out.write("                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Show All Alerts</a>\r\n");
          out.write("            </div>\r\n");
          out.write("        </li>\r\n");
          out.write("\r\n");
          out.write("        <!-- Nav Item - Messages -->\r\n");
          out.write("        <li class=\"nav-item dropdown no-arrow mx-1\">\r\n");
          out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                <i class=\"fas fa-envelope fa-fw\"></i>\r\n");
          out.write("                <!-- Counter - Messages -->\r\n");
          out.write("                <span class=\"badge badge-danger badge-counter\">7</span>\r\n");
          out.write("            </a>\r\n");
          out.write("            <!-- Dropdown - Messages -->\r\n");
          out.write("            <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"messagesDropdown\">\r\n");
          out.write("                <h6 class=\"dropdown-header\">\r\n");
          out.write("                    Message Center\r\n");
          out.write("                </h6>\r\n");
          out.write("                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
          out.write("                    <div class=\"dropdown-list-image mr-3\">\r\n");
          out.write("                        <img class=\"rounded-circle\" src=\"\" alt=\"...\">\r\n");
          out.write("                        <div class=\"status-indicator bg-success\"></div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div class=\"font-weight-bold\">\r\n");
          out.write("                        <div class=\"text-truncate\">Hi there! I am wondering if you can help me with a\r\n");
          out.write("                            problem I've been having.</div>\r\n");
          out.write("                        <div class=\"small text-gray-500\">Emily Fowler · 58m</div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </a>\r\n");
          out.write("                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
          out.write("                    <div class=\"dropdown-list-image mr-3\">\r\n");
          out.write("                        <img class=\"rounded-circle\" src=\"\" alt=\"...\">\r\n");
          out.write("                        <div class=\"status-indicator\"></div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div>\r\n");
          out.write("                        <div class=\"text-truncate\">I have the photos that you ordered last month, how\r\n");
          out.write("                            would you like them sent to you?</div>\r\n");
          out.write("                        <div class=\"small text-gray-500\">Jae Chun · 1d</div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </a>\r\n");
          out.write("                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
          out.write("                    <div class=\"dropdown-list-image mr-3\">\r\n");
          out.write("                        <img class=\"rounded-circle\" src=\"\" alt=\"...\">\r\n");
          out.write("                        <div class=\"status-indicator bg-warning\"></div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div>\r\n");
          out.write("                        <div class=\"text-truncate\">Last month's report looks great, I am very happy with\r\n");
          out.write("                            the progress so far, keep up the good work!</div>\r\n");
          out.write("                        <div class=\"small text-gray-500\">Morgan Alvarez · 2d</div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </a>\r\n");
          out.write("                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
          out.write("                    <div class=\"dropdown-list-image mr-3\">\r\n");
          out.write("                        <img class=\"rounded-circle\" src=\"https://source.unsplash.com/Mv9hjnEUHR4/60x60\" alt=\"...\">\r\n");
          out.write("                        <div class=\"status-indicator bg-success\"></div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div>\r\n");
          out.write("                        <div class=\"text-truncate\">Am I a good boy? The reason I ask is because someone\r\n");
          out.write("                            told me that people say this to all dogs, even if they aren't good...</div>\r\n");
          out.write("                        <div class=\"small text-gray-500\">Chicken the Dog · 2w</div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </a>\r\n");
          out.write("                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Read More Messages</a>\r\n");
          out.write("            </div>\r\n");
          out.write("        </li>\r\n");
          out.write("\r\n");
          out.write("        		<!-- 로그인을 했는데 관리자라면 -->\r\n");
          out.write("		");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/include/header.jsp(268,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.verify == 9 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<a class=\"nav-link mx-3\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/index\">ADMIN으로 가기</a>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
