/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2025-04-03 16:23:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid bg-gradient-primary min-vh-100\">\r\n");
      out.write("<div class=\"row justify-content-center\">\r\n");
      out.write("<div class=\"col-xl-10 col-lg-12 col-md-9\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card o-hidden border-0 shadow-lg my-5\">\r\n");
      out.write("        <div class=\"card-body p-0\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-6 d-none d-lg-block bg-login-image\">\r\n");
      out.write("<!--배경이미지-->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 \">\r\n");
      out.write("<div class=\"p-5\">\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("    <h1 class=\"h4 text-grey-900 mb-4\">\r\n");
      out.write("        Welcome Back!\r\n");
      out.write("    </h1>\r\n");
      out.write("<form method=\"post\" class=\"was-validated\">\r\n");
      out.write("    <div class=\"my-3\">\r\n");
      out.write("        <input\r\n");
      out.write("type=\"text\"\r\n");
      out.write("class=\"form-control form-control-user\" \r\n");
      out.write("placeholder=\"아이디를 입력하세요\" \r\n");
      out.write("name=\"userId\"   \r\n");
      out.write("required=\"required\"  \r\n");
      out.write("        />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("        <input\r\n");
      out.write("type=\"password\"\r\n");
      out.write("class=\"form-control form-control-user\" \r\n");
      out.write("placeholder=\"비밀번호를 입력하세요\" \r\n");
      out.write("name=\"userPass\" \r\n");
      out.write("required=\"required\"         \r\n");
      out.write("        />\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<div class=\"my-3\">\r\n");
      out.write("	<div class=\"custom-control custom-checkbox small\">\r\n");
      out.write("<input\r\n");
      out.write("type=\"checkbox\"\r\n");
      out.write("class=\"custom-control-input\"\r\n");
      out.write("id=\"customCheck\"\r\n");
      out.write("/>	\r\n");
      out.write("<label class=\"custom-control-label\" for=\"customCheck\">\r\n");
      out.write("Remeber Me\r\n");
      out.write("</label>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>     \r\n");
      out.write("    \r\n");
      out.write("    <p class=\"mb-3\">\r\n");
      out.write("        <input \r\n");
      out.write("        type=\"submit\"\r\n");
      out.write("        class=\"btn btn-primary btn-user btn-block\"\r\n");
      out.write("        value=\"로그인\"\r\n");
      out.write("        id=\"signin_btn\"\r\n");
      out.write("        name=\"signin_btn\"\r\n");
      out.write("        />\r\n");
      out.write("    </p>\r\n");
      out.write("    \r\n");
      out.write("    <hr/>\r\n");
      out.write("    <p class=\"mb-3\">\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/google\" class=\"btn btn-google btn-user btn-block\">\r\n");
      out.write("<i class=\"fab fa-google fa-fw\"></i>\r\n");
      out.write("&nbsp;Login with Google\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <p class=\"mb-3\">\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/face\" class=\"btn btn-facebook btn-user btn-block\">\r\n");
      out.write("<i class=\"fab fa-facebook fa-fw\"></i>\r\n");
      out.write("&nbsp;Login with Facebook\r\n");
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("    </p>\r\n");
      out.write("    \r\n");
      out.write("<hr/>\r\n");
      out.write("\r\n");
      out.write("<div class=\"mb-3\">\r\n");
      out.write("<a class=\"small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/forgot\">\r\n");
      out.write("forgot Password?\r\n");
      out.write("</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"mb-3\">\r\n");
      out.write("<a class=\"small\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/signup\">\r\n");
      out.write("join\r\n");
      out.write("</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
